server.port=8082
spring.application.name=mesatech-catalogo

# Base de datos MySQL (Amazon RDS o instancia EC2)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mesatech_catalogo_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:RootSecurePassword2026!}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
