server.port=8080
spring.application.name=mesatech-bff

# Perfil Producción / AWS EC2
azure.tenant-id=${AZURE_TENANT_ID}
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=${AZURE_AUDIENCE:api://api-cloud-native}

services.solicitudes.url=${SERVICES_SOLICITUDES_URL:http://mesatech-solicitudes:8081}
services.catalogo.url=${SERVICES_CATALOGO_URL:http://mesatech-catalogo:8082}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://mesatech.cloud}
